{{- if .Values.web.hpa.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "xboard.componentName" (dict "ctx" . "role" "web") }}
  labels:
    {{- include "xboard.componentLabels" (dict "ctx" . "role" "web") | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "xboard.componentName" (dict "ctx" . "role" "web") }}
  minReplicas: {{ .Values.web.hpa.minReplicas }}
  maxReplicas: {{ .Values.web.hpa.maxReplicas }}
  metrics:
    {{- toYaml .Values.web.hpa.metrics | nindent 4 }}
{{- end }}
