{{- if empty .Values.config.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "xboard.configSecretName" . }}
  labels:
    {{- include "xboard.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  {{- range $k, $v := .Values.config.values }}
  {{- if eq $k "APP_KEY" }}
  APP_KEY: {{ include "xboard.appKey" $ | quote }}
  {{- else }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
  {{- end }}
  {{- range $k, $v := .Values.config.extraValues }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
{{- end }}
